namespace ONIT.VismaNetApi.Models.Enums
{
    public enum ShipmentStatus
    {
        Open = 10,
        Hold = 20,
        Completed = 30,
        Cancelled = 40,
        Confirmed = 50,
        Invoiced = 60,
        Receipted = 70,
        AutoGenerated = 80,
        PartiallyInvoiced = 90,
    }
}